### ISSUE TITLE
작업

### ISSUE THREAD

**Issue by nsms556** [gaoneducation/BMONG_US#1]
기본
 - 스프라이트 레이어 순서 -> 메서드로 추출

~~맵~~
-  ~~충돌 구현~~

~~캐릭터~~
 - ~~임포스터, 크루원 -> 캐릭터 상속 받아서 분리~~
 - ~~크루원 이미지 작업~~

~~임포스터~~
 - ~~킬~~
   + ~~킬 모션~~
 - ~~사보타주~~

크루원
 - 랜덤 움직임

**Comment by yansigit** [comment]
칼라스왑하는거 브랜치 따로파서 올려놨음
https://github.com/gaoneducation/BMONG_US/blob/colorswap/_test.py
단독으로 작동은 무리없이 잘 되는데 게임에 적용하는건 자료형이 달라서 파일로 저장해놓고 하거나 자료형을 컨버팅하거나 바이트로 어떻게 하거나 해야할 거 같음

**Comment by yansigit** [comment]
파일로 저장해서 사용하는 방식으로 업데이트함
게임 잘 구동댐
